Top_1000_Voc = [
    {korean:"사람",  uzbek:"Odam",    type:"Noun"},
    {korean:"집",  uzbek:"Uy",    type:"Noun"},
    {korean:"차",  uzbek:"Avtomobil",    type:"Noun"},
    {korean:"학교",  uzbek:"Maktab",    type:"Noun"},
    {korean:"물",  uzbek:"Suv",    type:"Noun"},
    {korean:"사랑",  uzbek:"Sevgi",    type:"Noun"},
    {korean:"친구",  uzbek:"Do'st",    type:"Noun"},
    {korean:"가족",  uzbek:"Oila",    type:"Noun"},
    {korean:"하다",  uzbek:"qilmoq",    type:"Verb"},
    {korean:"가다",  uzbek:"bormoq",    type:"Verb"},
    {korean:"오다",  uzbek:"kelmoq",    type:"Verb"},
    {korean:"먹다",  uzbek:"yemoq",    type:"Verb"},
    {korean:"마시다",  uzbek:"ichmoq",    type:"Verb"},
    {korean:"자다",  uzbek:"uxlash",    type:"Verb"},
    {korean:"크다",  uzbek:"katta",    type:"Adjective"},
    {korean:"작다",  uzbek:"kichik",    type:"Adjective"},
    {korean:"좋다",  uzbek:"yaxshi",    type:"Adjective"},
    {korean:"나쁘다",  uzbek:"yomon",    type:"Adjective"},
    {korean:"빨리",  uzbek:"tez",    type:"Adverb"},
    {korean:"천천히",  uzbek:"sekin",    type:"Adverb"},
    {korean:"돈",  uzbek:"Pul",    type:"Noun"},
    {korean:"음식",  uzbek:"Ovqat",    type:"Noun"},
    {korean:"시간",  uzbek:"Vaqt",    type:"Noun"},
    {korean:"노래",  uzbek:"Qo'shiq",    type:"Noun"},
    {korean:"책",  uzbek:"Kitob",    type:"Noun"},
    {korean:"영화",  uzbek:"Kino",    type:"Noun"},
    {korean:"음악",  uzbek:"Musiqa",    type:"Noun"},
    {korean:"길",  uzbek:"Yo'l",    type:"Noun"},
    {korean:"일하다",  uzbek:"ishlamoq",    type:"Verb"},
    {korean:"공부하다",  uzbek:"o‘qimoq",    type:"Verb"},
    {korean:"보다",  uzbek:"ko‘rmoq",    type:"Verb"},
    {korean:"듣다",  uzbek:"eshitmoq",    type:"Verb"},
    {korean:"쓰다",  uzbek:"yozmoq",    type:"Verb"},
    {korean:"읽다",  uzbek:"o‘qimoq",    type:"Verb"},
    {korean:"빠르다",  uzbek:"tez",    type:"Adjective"},
    {korean:"느리다",  uzbek:"sekin",    type:"Adjective"},
    {korean:"높다",  uzbek:"baland",    type:"Adjective"},
    {korean:"낮다",  uzbek:"past",    type:"Adjective"},
    {korean:"잘",  uzbek:"yaxshi",    type:"Adverb"},
    {korean:"못",  uzbek:"yomon",    type:"Adverb"},
    {korean:"공원",  uzbek:"Bog'",    type:"Noun"},
    {korean:"시장",  uzbek:"Bozor",    type:"Noun"},
    {korean:"가게",  uzbek:"Do'kon",    type:"Noun"},
    {korean:"자동차",  uzbek:"Avtomobil",    type:"Noun"},
    {korean:"버스",  uzbek:"Avtobus",    type:"Noun"},
    {korean:"비행기",  uzbek:"Samolyot",    type:"Noun"},
    {korean:"여행",  uzbek:"Sayohat",    type:"Noun"},
    {korean:"바다",  uzbek:"Dengiz",    type:"Noun"},
    {korean:"말하다",  uzbek:"gapirmoq",    type:"Verb"},
    {korean:"만나다",  uzbek:"uchrashmoq",    type:"Verb"},
    {korean:"사다",  uzbek:"sotib olmoq",    type:"Verb"},
    {korean:"팔다",  uzbek:"sotmoq",    type:"Verb"},
    {korean:"앉다",  uzbek:"o‘tirmoq",    type:"Verb"},
    {korean:"서다",  uzbek:"tik turmoq",    type:"Verb"},
    {korean:"덥다",  uzbek:"issiq",    type:"Adjective"},
    {korean:"춥다",  uzbek:"sovuq",    type:"Adjective"},
    {korean:"길다",  uzbek:"uzun",    type:"Adjective"},
    {korean:"짧다",  uzbek:"qisqa",    type:"Adjective"},
    {korean:"많이",  uzbek:"ko‘p",    type:"Adverb"},
    {korean:"조금",  uzbek:"ozgina",    type:"Adverb"},
    {korean:"산",  uzbek:"Tog'",    type:"Noun"},
    {korean:"꽃",  uzbek:"Gul",    type:"Noun"},
    {korean:"나무",  uzbek:"Daraxt",    type:"Noun"},
    {korean:"하늘",  uzbek:"Osmon",    type:"Noun"},
    {korean:"구름",  uzbek:"Bulut",    type:"Noun"},
    {korean:"비",  uzbek:"Yomg'ir",    type:"Noun"},
    {korean:"눈",  uzbek:"Qor",    type:"Noun"},
    {korean:"날씨",  uzbek:"Ob-havo",    type:"Noun"},
    {korean:"타다",  uzbek:"minmoq",    type:"Verb"},
    {korean:"운전하다",  uzbek:"haydamoq",    type:"Verb"},
    {korean:"배우다",  uzbek:"o‘rganmoq",    type:"Verb"},
    {korean:"가르치다",  uzbek:"o‘rgatmoq",    type:"Verb"},
    {korean:"알다",  uzbek:"bilmoq",    type:"Verb"},
    {korean:"모르다",  uzbek:"bilmaslik",    type:"Verb"},
    {korean:"예쁘다",  uzbek:"chiroyli",    type:"Adjective"},
    {korean:"못생기다",  uzbek:"jo‘n",    type:"Adjective"},
    {korean:"깨끗하다",  uzbek:"toza",    type:"Adjective"},
    {korean:"더럽다",  uzbek:"iflos",    type:"Adjective"},
    {korean:"항상",  uzbek:"doimo",    type:"Adverb"},
    {korean:"가끔",  uzbek:"ba'zan",    type:"Adverb"},
    {korean:"날씨 - O",  uzbek:"avo",    type:"Noun"},
    {korean:"여름",  uzbek:"Yoz",    type:"Noun"},
    {korean:"가을",  uzbek:"Kuz",    type:"Noun"},
    {korean:"겨울",  uzbek:"Qish",    type:"Noun"},
    {korean:"봄",  uzbek:"Bahor",    type:"Noun"},
    {korean:"어제",  uzbek:"Kecha",    type:"Noun"},
    {korean:"오늘",  uzbek:"Bugun",    type:"Noun"},
    {korean:"내일",  uzbek:"Ertaga",    type:"Noun"},
    {korean:"생각하다",  uzbek:"o‘ylamoq",    type:"Verb"},
    {korean:"기다리다",  uzbek:"kutmoq",    type:"Verb"},
    {korean:"주다",  uzbek:"bermoq",    type:"Verb"},
    {korean:"받다",  uzbek:"olmoq",    type:"Verb"},
    {korean:"열다",  uzbek:"ochmoq",    type:"Verb"},
    {korean:"닫다",  uzbek:"yopmoq",    type:"Verb"},
    {korean:"비싸다",  uzbek:"qimmat",    type:"Adjective"},
    {korean:"싸다",  uzbek:"arzon",    type:"Adjective"},
    {korean:"건강하다",  uzbek:"sog‘lom",    type:"Adjective"},
    {korean:"아프다",  uzbek:"og‘riyotgan",    type:"Adjective"},
    {korean:"절대",  uzbek:"hech qachon",    type:"Adverb"},
    {korean:"오늘",  uzbek:"bugun",    type:"Adverb"},
    {korean:"남자",  uzbek:"Erkak",    type:"Noun"},
    {korean:"여자",  uzbek:"Ayol",    type:"Noun"},
    {korean:"아이",  uzbek:"Bola",    type:"Noun"},
    {korean:"부모",  uzbek:"Ota-ona",    type:"Noun"},
    {korean:"부모 - Ot",  uzbek:"na",    type:"Noun"},
    {korean:"형제",  uzbek:"Aka-uka",    type:"Noun"},
    {korean:"형제 - Ak",  uzbek:"ka",    type:"Noun"},
    {korean:"강아지",  uzbek:"Kucha iti",    type:"Noun"},
    {korean:"만들다",  uzbek:"yasamoq",    type:"Verb"},
    {korean:"고치다",  uzbek:"tuzatmoq",    type:"Verb"},
    {korean:"청소하다",  uzbek:"tozalamoq",    type:"Verb"},
    {korean:"준비하다",  uzbek:"tayyorlamoq",    type:"Verb"},
    {korean:"요리하다",  uzbek:"ovqat pishirmoq",    type:"Verb"},
    {korean:"시작하다",  uzbek:"boshlamoq",    type:"Verb"},
    {korean:"행복하다",  uzbek:"baxtli",    type:"Adjective"},
    {korean:"슬프다",  uzbek:"qayg‘uli",    type:"Adjective"},
    {korean:"배고프다",  uzbek:"och",    type:"Adjective"},
    {korean:"배부르다",  uzbek:"to‘q",    type:"Adjective"},
    {korean:"어제",  uzbek:"kecha",    type:"Adverb"},
    {korean:"내일",  uzbek:"ertaga",    type:"Adverb"},
    {korean:"고양이",  uzbek:"Mushuk",    type:"Noun"},
    {korean:"새",  uzbek:"Qush",    type:"Noun"},
    {korean:"물고기",  uzbek:"Baliq",    type:"Noun"},
    {korean:"동물",  uzbek:"Hayvon",    type:"Noun"},
    {korean:"생일",  uzbek:"Tug'ilgan kun",    type:"Noun"},
    {korean:"결혼",  uzbek:"Nikoh",    type:"Noun"},
    {korean:"이름",  uzbek:"Ism",    type:"Noun"},
    {korean:"전화",  uzbek:"Telefon",    type:"Noun"},
    {korean:"끝내다",  uzbek:"tugatmoq",    type:"Verb"},
    {korean:"웃다",  uzbek:"kulmoq",    type:"Verb"},
    {korean:"울다",  uzbek:"yig‘lamoq",    type:"Verb"},
    {korean:"춤추다",  uzbek:"raqsga tushmoq",    type:"Verb"},
    {korean:"노래하다",  uzbek:"qo‘shiq aytmoq",    type:"Verb"},
    {korean:"운동하다",  uzbek:"sport bilan shug‘ullanmoq",    type:"Verb"},
    {korean:"쉽다",  uzbek:"oson",    type:"Adjective"},
    {korean:"어렵다",  uzbek:"qiyin",    type:"Adjective"},
    {korean:"무겁다",  uzbek:"og‘ir",    type:"Adjective"},
    {korean:"가볍다",  uzbek:"yengil",    type:"Adjective"},
    {korean:"여기",  uzbek:"bu yerda",    type:"Adverb"},
    {korean:"저기",  uzbek:"u yerda",    type:"Adverb"},
    {korean:"컴퓨터",  uzbek:"Kompyuter",    type:"Noun"},
    {korean:"인터넷",  uzbek:"Internet",    type:"Noun"},
    {korean:"이메일",  uzbek:"Elektron pochta",    type:"Noun"},
    {korean:"사진",  uzbek:"Surat",    type:"Noun"},
    {korean:"영화관",  uzbek:"Kinoteatr",    type:"Noun"},
    {korean:"병원",  uzbek:"Kasalxona",    type:"Noun"},
    {korean:"약",  uzbek:"Dori",    type:"Noun"},
    {korean:"의사",  uzbek:"Shifokor",    type:"Noun"},
    {korean:"걷다",  uzbek:"piyoda yurmoq",    type:"Verb"},
    {korean:"달리다",  uzbek:"yugurmoq",    type:"Verb"},
    {korean:"쉬다",  uzbek:"dam olmoq",    type:"Verb"},
    {korean:"사랑하다",  uzbek:"sevmoq",    type:"Verb"},
    {korean:"싫어하다",  uzbek:"yoqtirmaslik",    type:"Verb"},
    {korean:"이해하다",  uzbek:"tushunmoq",    type:"Verb"},
    {korean:"재미있다",  uzbek:"qiziqarli",    type:"Adjective"},
    {korean:"지루하다",  uzbek:"zerikarli",    type:"Adjective"},
    {korean:"귀엽다",  uzbek:"qiziqarli",    type:"Adjective"},
    {korean:"아름답다",  uzbek:"go‘zal",    type:"Adjective"},
    {korean:"안",  uzbek:"ichida",    type:"Adverb"},
    {korean:"밖에",  uzbek:"tashqarida",    type:"Adverb"},
    {korean:"간호사",  uzbek:"Hamshira",    type:"Noun"},
    {korean:"경찰",  uzbek:"Militsiya",    type:"Noun"},
    {korean:"소방관",  uzbek:"O't o'chiruvchi",    type:"Noun"},
    {korean:"교사",  uzbek:"O'qituvchi",    type:"Noun"},
    {korean:"학생",  uzbek:"Talaba",    type:"Noun"},
    {korean:"회사원",  uzbek:"Ofis xodimi",    type:"Noun"},
    {korean:"은행",  uzbek:"Bank",    type:"Noun"},
    {korean:"신용카드",  uzbek:"Kredit karta",    type:"Noun"},
    {korean:"기억하다",  uzbek:"eslamoq",    type:"Verb"},
    {korean:"잊다",  uzbek:"unutmoq",    type:"Verb"},
    {korean:"도와주다",  uzbek:"yordam bermoq",    type:"Verb"},
    {korean:"사용하다",  uzbek:"ishlatmoq",    type:"Verb"},
    {korean:"필요하다",  uzbek:"kerak bo‘lmoq",    type:"Verb"},
    {korean:"원하다",  uzbek:"xohlamoq",    type:"Verb"},
    {korean:"똑똑하다",  uzbek:"aqlli",    type:"Adjective"},
    {korean:"멍청하다",  uzbek:"ahmoq",    type:"Adjective"},
    {korean:"달다",  uzbek:"shirin",    type:"Adjective"},
    {korean:"쓰다",  uzbek:"achchiq",    type:"Adjective"},
    {korean:"위에",  uzbek:"ustida",    type:"Adverb"},
    {korean:"아래에",  uzbek:"ostida",    type:"Adverb"},
    {korean:"쇼핑",  uzbek:"Xarid qilish",    type:"Noun"},
    {korean:"옷",  uzbek:"Kiyim",    type:"Noun"},
    {korean:"신발",  uzbek:"Oyoq kiyim",    type:"Noun"},
    {korean:"모자",  uzbek:"Bosh kiyim",    type:"Noun"},
    {korean:"안경",  uzbek:"Ko'zoynak",    type:"Noun"},
    {korean:"시계",  uzbek:"Soat",    type:"Noun"},
    {korean:"지갑",  uzbek:"Hamyon",    type:"Noun"},
    {korean:"가방",  uzbek:"Sumka",    type:"Noun"},
    {korean:"싫어하다",  uzbek:"yoqtirmaslik",    type:"Verb"},
    {korean:"좋아하다",  uzbek:"yoqtirmoq",    type:"Verb"},
    {korean:"살다",  uzbek:"yashamoq",    type:"Verb"},
    {korean:"죽다",  uzbek:"o‘lmoq",    type:"Verb"},
    {korean:"보내다",  uzbek:"jo‘natmoq",    type:"Verb"},
    {korean:"바라보다",  uzbek:"qaramoq",    type:"Verb"},
    {korean:"짜다",  uzbek:"tuzli",    type:"Adjective"},
    {korean:"맵다",  uzbek:"o'tkir",    type:"Adjective"},
    {korean:"시원하다",  uzbek:"serin",    type:"Adjective"},
    {korean:"따뜻하다",  uzbek:"iliq",    type:"Adjective"},
    {korean:"옆에",  uzbek:"yonida",    type:"Adverb"},
    {korean:"멀리",  uzbek:"uzoq",    type:"Adverb"},
    {korean:"음식점",  uzbek:"Restoran",    type:"Noun"},
    {korean:"커피",  uzbek:"Qahva",    type:"Noun"},
    {korean:"차",  uzbek:"Choy",    type:"Noun"},
    {korean:"맥주",  uzbek:"Pivo",    type:"Noun"},
    {korean:"와인",  uzbek:"Sharob",    type:"Noun"},
    {korean:"우유",  uzbek:"Sut",    type:"Noun"},
    {korean:"주스",  uzbek:"Sharbat",    type:"Noun"},
    {korean:"사과",  uzbek:"Olma",    type:"Noun"},
    {korean:"기다리다",  uzbek:"kutmoq",    type:"Verb"},
    {korean:"먹이다",  uzbek:"ovqatlantirmoq",    type:"Verb"},
    {korean:"씻다",  uzbek:"yuvmoq",    type:"Verb"},
    {korean:"준비하다",  uzbek:"tayyorlamoq",    type:"Verb"},
    {korean:"요리하다",  uzbek:"ovqat tayyorlamoq",    type:"Verb"},
    {korean:"가져오다",  uzbek:"olib kelmoq",    type:"Verb"},
    {korean:"차갑다",  uzbek:"sovuq (tutish uchun)",    type:"Adjective"},
    {korean:"뜨겁다",  uzbek:"issiq (tutish uchun)",    type:"Adjective"},
    {korean:"편하다",  uzbek:"qulay",    type:"Adjective"},
    {korean:"불편하다",  uzbek:"noqulay",    type:"Adjective"},
    {korean:"가까이",  uzbek:"yaqin",    type:"Adverb"},
    {korean:"같이",  uzbek:"birga",    type:"Adverb"},
    {korean:"바나나",  uzbek:"Banan",    type:"Noun"},
    {korean:"포도",  uzbek:"Uzum",    type:"Noun"},
    {korean:"오렌지",  uzbek:"Apelsin",    type:"Noun"},
    {korean:"딸기",  uzbek:"Qulupnay",    type:"Noun"},
    {korean:"수박",  uzbek:"Tarvuz",    type:"Noun"},
    {korean:"야채",  uzbek:"Sabzavot",    type:"Noun"},
    {korean:"채소",  uzbek:"Ko'katlar",    type:"Noun"},
    {korean:"고기",  uzbek:"Go'sht",    type:"Noun"},
    {korean:"부르다",  uzbek:"chaqirmoq",    type:"Verb"},
    {korean:"내다",  uzbek:"chiqarib bermoq",    type:"Verb"},
    {korean:"설명하다",  uzbek:"tushuntirmoq",    type:"Verb"},
    {korean:"떠나다",  uzbek:"ketmoq",    type:"Verb"},
    {korean:"꿈꾸다",  uzbek:"orzu qilmoq",    type:"Verb"},
    {korean:"일어나다",  uzbek:"uyg‘onmoq",    type:"Verb"},
    {korean:"흥미롭다",  uzbek:"qiziqarli",    type:"Adjective"},
    {korean:"중요한",  uzbek:"muhim",    type:"Adjective"},
    {korean:"특별하다",  uzbek:"maxsus",    type:"Adjective"},
    {korean:"평범하다",  uzbek:"oddiy",    type:"Adjective"},
    {korean:"따로",  uzbek:"alohida",    type:"Adverb"},
    {korean:"조용히",  uzbek:"jim",    type:"Adverb"},
    {korean:"닭고기",  uzbek:"Tovuq go'shti",    type:"Noun"},
    {korean:"돼지고기",  uzbek:"Cho'chqa go'shti",    type:"Noun"},
    {korean:"소고기",  uzbek:"Mol go'shti",    type:"Noun"},
    {korean:"생선",  uzbek:"Baliq",    type:"Noun"},
    {korean:"새우",  uzbek:"Krevetka",    type:"Noun"},
    {korean:"게",  uzbek:"Qisqichbaqa",    type:"Noun"},
    {korean:"쌀",  uzbek:"Guruch",    type:"Noun"},
    {korean:"빵",  uzbek:"Non",    type:"Noun"},
    {korean:"잡다",  uzbek:"ushlamoq",    type:"Verb"},
    {korean:"놓다",  uzbek:"qo‘ymoq",    type:"Verb"},
    {korean:"사라지다",  uzbek:"yo‘qolmoq",    type:"Verb"},
    {korean:"타다",  uzbek:"minmoq",    type:"Verb"},
    {korean:"끓이다",  uzbek:"qaynatmoq",    type:"Verb"},
    {korean:"보이다",  uzbek:"ko‘rinmoq",    type:"Verb"},
    {korean:"진지하다",  uzbek:"jiddiy",    type:"Adjective"},
    {korean:"어색하다",  uzbek:"noqulay",    type:"Adjective"},
    {korean:"부드럽다",  uzbek:"yumshoq",    type:"Adjective"},
    {korean:"단단하다",  uzbek:"qattiq",    type:"Adjective"},
    {korean:"시끄럽게",  uzbek:"shovqin bilan",    type:"Adverb"},
    {korean:"완전히",  uzbek:"to‘liq",    type:"Adverb"},
    {korean:"국수",  uzbek:"Lag'mon",    type:"Noun"},
    {korean:"계란",  uzbek:"Tuxum",    type:"Noun"},
    {korean:"버섯",  uzbek:"Qo'ziqorin",    type:"Noun"},
    {korean:"양파",  uzbek:"Piyoz",    type:"Noun"},
    {korean:"마늘",  uzbek:"Sarimsoq",    type:"Noun"},
    {korean:"감자",  uzbek:"Kartoshka",    type:"Noun"},
    {korean:"당근",  uzbek:"Sabzi",    type:"Noun"},
    {korean:"토마토",  uzbek:"Pomidor",    type:"Noun"},
    {korean:"대답하다",  uzbek:"javob bermoq",    type:"Verb"},
    {korean:"물어보다",  uzbek:"so‘ramoq",    type:"Verb"},
    {korean:"믿다",  uzbek:"ishonmoq",    type:"Verb"},
    {korean:"부탁하다",  uzbek:"iltimos qilmoq",    type:"Verb"},
    {korean:"잃다",  uzbek:"yo‘qotmoq",    type:"Verb"},
    {korean:"만지다",  uzbek:"ushlamoq",    type:"Verb"},
    {korean:"뚜렷하다",  uzbek:"aniq",    type:"Adjective"},
    {korean:"흐릿하다",  uzbek:"xiralashgan",    type:"Adjective"},
    {korean:"강하다",  uzbek:"kuchli",    type:"Adjective"},
    {korean:"약하다",  uzbek:"kuchsiz",    type:"Adjective"},
    {korean:"거의",  uzbek:"deyarli",    type:"Adverb"},
    {korean:"매우",  uzbek:"juda",    type:"Adverb"},
    {korean:"옥수수",  uzbek:"Makkajo'xori",    type:"Noun"},
    {korean:"상추",  uzbek:"Salat bargi",    type:"Noun"},
    {korean:"소금",  uzbek:"Tuz",    type:"Noun"},
    {korean:"설탕",  uzbek:"Shakar",    type:"Noun"},
    {korean:"후추",  uzbek:"Murch",    type:"Noun"},
    {korean:"고추",  uzbek:"Qalampir",    type:"Noun"},
    {korean:"식초",  uzbek:"Sirka",    type:"Noun"},
    {korean:"간장",  uzbek:"Soya sousi",    type:"Noun"},
    {korean:"설치하다",  uzbek:"o‘rnatmoq",    type:"Verb"},
    {korean:"입다",  uzbek:"kiyib olmoq",    type:"Verb"},
    {korean:"벗다",  uzbek:"yechmoq",    type:"Verb"},
    {korean:"이사하다",  uzbek:"ko‘chmoq",    type:"Verb"},
    {korean:"초대하다",  uzbek:"taklif qilmoq",    type:"Verb"},
    {korean:"약속하다",  uzbek:"va'da bermoq",    type:"Verb"},
    {korean:"상큼하다",  uzbek:"toza, tetik",    type:"Adjective"},
    {korean:"답답하다",  uzbek:"siqilmoq",    type:"Adjective"},
    {korean:"기쁘다",  uzbek:"xursand",    type:"Adjective"},
    {korean:"화나다",  uzbek:"g‘azablangan",    type:"Adjective"},
    {korean:"정말",  uzbek:"haqiqatan",    type:"Adverb"},
    {korean:"자주",  uzbek:"tez-tez",    type:"Adverb"},
    {korean:"된장",  uzbek:"Soya loviya pastasi",    type:"Noun"},
    {korean:"고추장",  uzbek:"Qizil qalampir pastasi",    type:"Noun"},
    {korean:"참기름",  uzbek:"Kunjut yog'i",    type:"Noun"},
    {korean:"식용유",  uzbek:"Oshpazlik yog'i",    type:"Noun"},
    {korean:"치킨",  uzbek:"Tovuq",    type:"Noun"},
    {korean:"피자",  uzbek:"Pizza",    type:"Noun"},
    {korean:"햄버거",  uzbek:"Gamburger",    type:"Noun"},
    {korean:"스파게티",  uzbek:"Spagetti",    type:"Noun"},
    {korean:"기르다",  uzbek:"o'stirmoq",    type:"Verb"},
    {korean:"걱정하다",  uzbek:"xavotir olmq",    type:"Verb"},
    {korean:"저축하다",  uzbek:"jamg‘armoq",    type:"Verb"},
    {korean:"소비하다",  uzbek:"sarflamoq",    type:"Verb"},
    {korean:"다치다",  uzbek:"jarohatlanmoq",    type:"Verb"},
    {korean:"성공하다",  uzbek:"muvaffaqiyat qozonmoq",    type:"Verb"},
    {korean:"놀랍다",  uzbek:"hayratlanarli",    type:"Adjective"},
    {korean:"평화롭다",  uzbek:"tinch",    type:"Adjective"},
    {korean:"무질서하다",  uzbek:"tartibsiz",    type:"Adjective"},
    {korean:"질서 있다",  uzbek:"tartibli",    type:"Adjective"},
    {korean:"매일",  uzbek:"har kuni",    type:"Adverb"},
    {korean:"언제나",  uzbek:"har doim",    type:"Adverb"},
    {korean:"샐러드",  uzbek:"Salat",    type:"Noun"},
    {korean:"아이스크림",  uzbek:"Muzqaymoq",    type:"Noun"},
    {korean:"케이크",  uzbek:"Pirojnoe",    type:"Noun"},
    {korean:"쿠키",  uzbek:"Pechenye",    type:"Noun"},
    {korean:"초콜릿",  uzbek:"Shokolad",    type:"Noun"},
    {korean:"사탕",  uzbek:"Konfet",    type:"Noun"},
    {korean:"국",  uzbek:"Sho'rva",    type:"Noun"},
    {korean:"찌개",  uzbek:"Qovurma sho'rva",    type:"Noun"},
    {korean:"실패하다",  uzbek:"muvaffaqiyatsizlikka uchramoq",    type:"Verb"},
    {korean:"적다",  uzbek:"yozmoq",    type:"Verb"},
    {korean:"계획하다",  uzbek:"rejalashtirmoq",    type:"Verb"},
    {korean:"조절하다",  uzbek:"boshqarish",    type:"Verb"},
    {korean:"가르치다",  uzbek:"o‘rgatmoq",    type:"Verb"},
    {korean:"대답하다",  uzbek:"javob bermoq",    type:"Verb"},
    {korean:"안전하다",  uzbek:"xavfsiz",    type:"Adjective"},
    {korean:"위험하다",  uzbek:"xavfli",    type:"Adjective"},
    {korean:"재미있다",  uzbek:"qiziqarli",    type:"Adjective"},
    {korean:"자랑스럽다",  uzbek:"faxrlanuvchi",    type:"Adjective"},
    {korean:"갑자기",  uzbek:"birdan",    type:"Adverb"},
    {korean:"이미",  uzbek:"allaqachon",    type:"Adverb"},
    {korean:"반찬",  uzbek:"Garnir",    type:"Noun"},
    {korean:"김치",  uzbek:"Kimchi",    type:"Noun"},
    {korean:"김밥",  uzbek:"Kimbap",    type:"Noun"},
    {korean:"비빔밥",  uzbek:"Bibimbap",    type:"Noun"},
    {korean:"불고기",  uzbek:"Bulgogi",    type:"Noun"},
    {korean:"떡",  uzbek:"Guruchli pirog",    type:"Noun"},
    {korean:"만두",  uzbek:"Xonimlar",    type:"Noun"},
    {korean:"떡볶이",  uzbek:"Achchiq guruch pirogi",    type:"Noun"},
    {korean:"보내다",  uzbek:"jo‘natmoq",    type:"Verb"},
    {korean:"나오다",  uzbek:"chiqmoq",    type:"Verb"},
    {korean:"들어가다",  uzbek:"kirib bormoq",    type:"Verb"},
    {korean:"살펴보다",  uzbek:"o‘rganmoq",    type:"Verb"},
    {korean:"빌리다",  uzbek:"ijaraga olmoq",    type:"Verb"},
    {korean:"생각하다",  uzbek:"o‘ylamoq",    type:"Verb"},
    {korean:"친절하다",  uzbek:"mehribon",    type:"Adjective"},
    {korean:"엄격하다",  uzbek:"qat'iy",    type:"Adjective"},
    {korean:"허술하다",  uzbek:"ehtiyotsiz",    type:"Adjective"},
    {korean:"고요하다",  uzbek:"tinch",    type:"Adjective"},
    {korean:"다시",  uzbek:"yana",    type:"Adverb"},
    {korean:"한번",  uzbek:"bir marta",    type:"Adverb"},
    {korean:"잡채",  uzbek:"Japchae (koreyscha osh)",    type:"Noun"},
    {korean:"순두부",  uzbek:"Yumshoq tofu",    type:"Noun"},
    {korean:"냉면",  uzbek:"Sovuq lag'mon",    type:"Noun"},
    {korean:"삼계탕",  uzbek:"Ginsengli tovuq sho'rvasi",    type:"Noun"},
    {korean:"설렁탕",  uzbek:"Mol suyakli sho'rva",    type:"Noun"},
    {korean:"갈비",  uzbek:"Qovurg'a",    type:"Noun"},
    {korean:"탕수육",  uzbek:"Shirin va nordon cho'chqa go'shti",    type:"Noun"},
    {korean:"전",  uzbek:"Pankeyk",    type:"Noun"},
    {korean:"설명하다",  uzbek:"tushuntirmoq",    type:"Verb"},
    {korean:"인사하다",  uzbek:"salomlashmoq",    type:"Verb"},
    {korean:"결정하다",  uzbek:"qaror qilmoq",    type:"Verb"},
    {korean:"발견하다",  uzbek:"topmoq",    type:"Verb"},
    {korean:"잊다",  uzbek:"unutmoq",    type:"Verb"},
    {korean:"실행하다",  uzbek:"bajarish",    type:"Verb"},
    {korean:"쾌적하다",  uzbek:"qulay",    type:"Adjective"},
    {korean:"더럽다",  uzbek:"iflos",    type:"Adjective"},
    {korean:"만족스럽다",  uzbek:"mamnun",    type:"Adjective"},
    {korean:"기분 좋다",  uzbek:"kayfiyat yaxshi",    type:"Adjective"},
    {korean:"두번",  uzbek:"ikki marta",    type:"Adverb"},
    {korean:"세번",  uzbek:"uch marta",    type:"Adverb"},
    {korean:"김",  uzbek:"Dengiz o'tlari",    type:"Noun"},
    {korean:"미역",  uzbek:"Dengiz o'tlari sho'rvasi",    type:"Noun"},
    {korean:"된장찌개",  uzbek:"Soya loviya sho'rvasi",    type:"Noun"},
    {korean:"김치찌개",  uzbek:"Kimchi sho'rvasi",    type:"Noun"},
    {korean:"떡국",  uzbek:"Guruch sho'rvasi",    type:"Noun"},
    {korean:"북어국",  uzbek:"Quritilgan balikli sho'rva",    type:"Noun"},
    {korean:"순두부찌개",  uzbek:"Yumshoq tofu sho'rvasi",    type:"Noun"},
    {korean:"오이김치",  uzbek:"Bodring kimchisi",    type:"Noun"},
    {korean:"즐기다",  uzbek:"rohatlanmoq",    type:"Verb"},
    {korean:"입다",  uzbek:"kiyish",    type:"Verb"},
    {korean:"지키다",  uzbek:"saqlamoq",    type:"Verb"},
    {korean:"믿다",  uzbek:"ishonmoq",    type:"Verb"},
    {korean:"닫다",  uzbek:"yopmoq",    type:"Verb"},
    {korean:"켜다",  uzbek:"yoqmoq",    type:"Verb"},
    {korean:"기분 나쁘다",  uzbek:"kayfiyat yomon",    type:"Adjective"},
    {korean:"차분하다",  uzbek:"xotirjam",    type:"Adjective"},
    {korean:"시끄럽다",  uzbek:"shovqinli",    type:"Adjective"},
    {korean:"느긋하다",  uzbek:"sokin",    type:"Adjective"},
    {korean:"자주",  uzbek:"tez-tez",    type:"Adverb"},
    {korean:"늘",  uzbek:"doim",    type:"Adverb"},
    {korean:"열무김치",  uzbek:"Yosh turp kimchisi",    type:"Noun"},
    {korean:"깍두기",  uzbek:"Turp kimchisi",    type:"Noun"},
    {korean:"동치미",  uzbek:"Suvli kimchi",    type:"Noun"},
    {korean:"장아찌",  uzbek:"Tuzlangan sabzavotlar",    type:"Noun"},
    {korean:"조림",  uzbek:"Qovurilgan taom",    type:"Noun"},
    {korean:"나물",  uzbek:"Ziravorlangan sabzavotlar",    type:"Noun"},
    {korean:"샤브샤브",  uzbek:"Shabu-shabu",    type:"Noun"},
    {korean:"샤브샤브 - Shab",  uzbek:"habu",    type:"Noun"},
    {korean:"변화하다",  uzbek:"o'zgarish",    type:"Verb"},
    {korean:"진행하다",  uzbek:"davom ettirmoq",    type:"Verb"},
    {korean:"수영하다",  uzbek:"suzmoq",    type:"Verb"},
    {korean:"다치다",  uzbek:"jarohatlanmoq",    type:"Verb"},
    {korean:"수확하다",  uzbek:"yig‘ish (hosil)",    type:"Verb"},
    {korean:"제공하다",  uzbek:"taqdim etmoq",    type:"Verb"},
    {korean:"조용하다",  uzbek:"jim",    type:"Adjective"},
    {korean:"성실하다",  uzbek:"samimiy",    type:"Adjective"},
    {korean:"정직하다",  uzbek:"rostgo‘y",    type:"Adjective"},
    {korean:"신중하다",  uzbek:"ehtiyotkor",    type:"Adjective"},
    {korean:"오늘밤",  uzbek:"bugun kechqurun",    type:"Adverb"},
    {korean:"어젯밤",  uzbek:"kecha kechqurun",    type:"Adverb"},
    {korean:"오므라이스",  uzbek:"Omletli guruch",    type:"Noun"},
    {korean:"오야코동",  uzbek:"Tovuq va tuxumli guruch",    type:"Noun"},
    {korean:"돈가스",  uzbek:"Tonkatsu",    type:"Noun"},
    {korean:"덮밥",  uzbek:"Guruchli taom",    type:"Noun"},
    {korean:"카레라이스",  uzbek:"Kare guruchi",    type:"Noun"},
    {korean:"우동",  uzbek:"Udon",    type:"Noun"},
    {korean:"소바",  uzbek:"Soba",    type:"Noun"},
    {korean:"라멘",  uzbek:"Ramen",    type:"Noun"},
    {korean:"사용하다",  uzbek:"ishlatmoq",    type:"Verb"},
    {korean:"평가하다",  uzbek:"baholamoq",    type:"Verb"},
    {korean:"조사하다",  uzbek:"tadqiqot qilmoq",    type:"Verb"},
    {korean:"수출하다",  uzbek:"eksport qilmoq",    type:"Verb"},
    {korean:"진화하다",  uzbek:"rivojlanmoq",    type:"Verb"},
    {korean:"발전하다",  uzbek:"taraqqiy etmoq",    type:"Verb"},
    {korean:"유연하다",  uzbek:"moslashuvchan",    type:"Adjective"},
    {korean:"부지런하다",  uzbek:"mehnatkash",    type:"Adjective"},
    {korean:"귀찮다",  uzbek:"zerikkan",    type:"Adjective"},
    {korean:"근면하다",  uzbek:"intizomli",    type:"Adjective"},
    {korean:"매주",  uzbek:"har hafta",    type:"Adverb"},
    {korean:"매월",  uzbek:"har oy",    type:"Adverb"},
    {korean:"초밥",  uzbek:"Suşi",    type:"Noun"},
    {korean:"사시미",  uzbek:"Sashimi",    type:"Noun"},
    {korean:"타코야끼",  uzbek:"Takoyaki",    type:"Noun"},
    {korean:"오코노미야끼",  uzbek:"Okonomiyaki",    type:"Noun"},
    {korean:"팥빙수",  uzbek:"Muzli loviya deserti",    type:"Noun"},
    {korean:"단팥죽",  uzbek:"Shirin qizil loviya sho'rvasi",    type:"Noun"},
    {korean:"인절미",  uzbek:"Soya unli guruch pirogi",    type:"Noun"},
    {korean:"약과",  uzbek:"Koreyscha pirojnoe",    type:"Noun"},
    {korean:"예측하다",  uzbek:"bashorat qilmoq",    type:"Verb"},
    {korean:"경험하다",  uzbek:"tajriba orttirmoq",    type:"Verb"},
    {korean:"증명하다",  uzbek:"isbotlamoq",    type:"Verb"},
    {korean:"제안하다",  uzbek:"taklif qilmoq",    type:"Verb"},
    {korean:"연결하다",  uzbek:"bog‘lamoq",    type:"Verb"},
    {korean:"결합하다",  uzbek:"birlashtirmoq",    type:"Verb"},
    {korean:"소중하다",  uzbek:"qadrli",    type:"Adjective"},
    {korean:"화려하다",  uzbek:"chiroyli, ajoyib",    type:"Adjective"},
    {korean:"슬프다",  uzbek:"g‘amgin",    type:"Adjective"},
    {korean:"유용하다",  uzbek:"foydali",    type:"Adjective"},
    {korean:"매년",  uzbek:"har yil",    type:"Adverb"},
    {korean:"정말로",  uzbek:"haqiqatan",    type:"Adverb"},
    {korean:"한과",  uzbek:"Koreyscha shirinliklar",    type:"Noun"},
    {korean:"유과",  uzbek:"Koreyscha guruch puflari",    type:"Noun"},
    {korean:"전통차",  uzbek:"An'anaviy choy",    type:"Noun"},
    {korean:"녹차",  uzbek:"Yashil choy",    type:"Noun"},
    {korean:"홍차",  uzbek:"Qora choy",    type:"Noun"},
    {korean:"매실차",  uzbek:"Olxo'ri choyi",    type:"Noun"},
    {korean:"유자차",  uzbek:"Sitron choyi",    type:"Noun"},
    {korean:"대추차",  uzbek:"Jujube choyi",    type:"Noun"},
    {korean:"조정하다",  uzbek:"sozlash",    type:"Verb"},
    {korean:"확인하다",  uzbek:"tekshirmoq",    type:"Verb"},
    {korean:"가다",  uzbek:"bormoq",    type:"Verb"},
    {korean:"오다",  uzbek:"kelmoq",    type:"Verb"},
    {korean:"나오다",  uzbek:"chiqmoq",    type:"Verb"},
    {korean:"들어가다",  uzbek:"kirib bormoq",    type:"Verb"},
    {korean:"괜찮다",  uzbek:"yaxshi",    type:"Adjective"},
    {korean:"시원하다",  uzbek:"salqin",    type:"Adjective"},
    {korean:"촉촉하다",  uzbek:"nam",    type:"Adjective"},
    {korean:"맑다",  uzbek:"tiniq",    type:"Adjective"},
    {korean:"그냥",  uzbek:"shunchaki",    type:"Adverb"},
    {korean:"제대로",  uzbek:"to‘g‘ri",    type:"Adverb"},
    {korean:"생강차",  uzbek:"Zanjabil choyi",    type:"Noun"},
    {korean:"오미자차",  uzbek:"Shizandra choyi",    type:"Noun"},
    {korean:"숭늉",  uzbek:"Qovurilgan guruch choyi",    type:"Noun"},
    {korean:"식혜",  uzbek:"Shirin guruch ichimligi",    type:"Noun"},
    {korean:"수정과",  uzbek:"Dolchin ichimligi",    type:"Noun"},
    {korean:"막걸리",  uzbek:"Guruch sharobi",    type:"Noun"},
    {korean:"소주",  uzbek:"Soju",    type:"Noun"},
    {korean:"청주",  uzbek:"An'anaviy sharob",    type:"Noun"},
    {korean:"나가다",  uzbek:"chiqib bormoq",    type:"Verb"},
    {korean:"보이다",  uzbek:"ko‘rinmoq",    type:"Verb"},
    {korean:"자다",  uzbek:"uxlash",    type:"Verb"},
    {korean:"일어나다",  uzbek:"turmoq",    type:"Verb"},
    {korean:"끓다",  uzbek:"qaynamoq",    type:"Verb"},
    {korean:"하다",  uzbek:"qilmoq",    type:"Verb"},
    {korean:"흐리다",  uzbek:"bulutli",    type:"Adjective"},
    {korean:"평화롭다",  uzbek:"tinch",    type:"Adjective"},
    {korean:"화려하다",  uzbek:"o'ziga jalb qiluvchi",    type:"Adjective"},
    {korean:"혼란스럽다",  uzbek:"chalkash",    type:"Adjective"},
    {korean:"바로",  uzbek:"darhol",    type:"Adverb"},
    {korean:"대체로",  uzbek:"umuman",    type:"Adverb"},
    {korean:"복분자주",  uzbek:"Malinali sharob",    type:"Noun"},
    {korean:"매화수",  uzbek:"Olxo'ri sharobi",    type:"Noun"},
    {korean:"칵테일",  uzbek:"Kokteyl",    type:"Noun"},
    {korean:"양주",  uzbek:"Viski",    type:"Noun"},
    {korean:"보드카",  uzbek:"Vodka",    type:"Noun"},
    {korean:"럼",  uzbek:"Rum",    type:"Noun"},
    {korean:"테킬라",  uzbek:"Tekila",    type:"Noun"},
    {korean:"브랜디",  uzbek:"Brendi",    type:"Noun"},
    {korean:"보장하다",  uzbek:"kafolat bermoq",    type:"Verb"},
    {korean:"포함하다",  uzbek:"o‘z ichiga olmoq",    type:"Verb"},
    {korean:"섞다",  uzbek:"aralashtirmoq",    type:"Verb"},
    {korean:"따르다",  uzbek:"ergashmoq",    type:"Verb"},
    {korean:"안다",  uzbek:"bilmoq",    type:"Verb"},
    {korean:"원하다",  uzbek:"xohlamoq",    type:"Verb"},
    {korean:"단순하다",  uzbek:"oddiy",    type:"Adjective"},
    {korean:"복잡하다",  uzbek:"murakkab",    type:"Adjective"},
    {korean:"차가운",  uzbek:"sovuq",    type:"Adjective"},
    {korean:"따뜻한",  uzbek:"iliq",    type:"Adjective"},
    {korean:"혹시",  uzbek:"ehtimol",    type:"Adverb"},
    {korean:"별로",  uzbek:"unchalik emas",    type:"Adverb"},
    {korean:"코냑",  uzbek:"Konyak",    type:"Noun"},
    {korean:"진",  uzbek:"Jin",    type:"Noun"},
    {korean:"샴페인",  uzbek:"Shampan",    type:"Noun"},
    {korean:"무알콜",  uzbek:"Spirtli emas",    type:"Noun"},
    {korean:"음료수",  uzbek:"Ichimlik",    type:"Noun"},
    {korean:"탄산수",  uzbek:"Gazli suv",    type:"Noun"},
    {korean:"콜라",  uzbek:"Kola",    type:"Noun"},
    {korean:"사이다",  uzbek:"Soda",    type:"Noun"},
    {korean:"수긍하다",  uzbek:"rozilik bermoq",    type:"Verb"},
    {korean:"기부하다",  uzbek:"xayriya qilmoq",    type:"Verb"},
    {korean:"복원하다",  uzbek:"tiklamoq",    type:"Verb"},
    {korean:"가리키다",  uzbek:"ko‘rsatmoq",    type:"Verb"},
    {korean:"만들다",  uzbek:"yasamoq",    type:"Verb"},
    {korean:"찾다",  uzbek:"topmoq",    type:"Verb"},
    {korean:"불쾌하다",  uzbek:"noqulay",    type:"Adjective"},
    {korean:"안전한",  uzbek:"xavfsiz",    type:"Adjective"},
    {korean:"위험한",  uzbek:"xavfli",    type:"Adjective"},
    {korean:"익숙하다",  uzbek:"tanish",    type:"Adjective"},
    {korean:"결국",  uzbek:"natijada",    type:"Adverb"},
    {korean:"급히",  uzbek:"shoshilinch",    type:"Adverb"},
    {korean:"주스",  uzbek:"Sharbat",    type:"Noun"},
    {korean:"오렌지주스",  uzbek:"Apelsin sharbat",    type:"Noun"},
    {korean:"사과주스",  uzbek:"Olma sharbat",    type:"Noun"},
    {korean:"포도주스",  uzbek:"Uzum sharbat",    type:"Noun"},
    {korean:"토마토주스",  uzbek:"Pomidor sharbat",    type:"Noun"},
    {korean:"망고주스",  uzbek:"Mango sharbat",    type:"Noun"},
    {korean:"딸기주스",  uzbek:"Qulupnay sharbat",    type:"Noun"},
    {korean:"요구르트",  uzbek:"Yogurt",    type:"Noun"},
    {korean:"발전하다",  uzbek:"taraqqiy etmoq",    type:"Verb"},
    {korean:"조정하다",  uzbek:"moslashtirmoq",    type:"Verb"},
    {korean:"반복하다",  uzbek:"takrorlamoq",    type:"Verb"},
    {korean:"회복하다",  uzbek:"tiklamoq",    type:"Verb"},
    {korean:"처리하다",  uzbek:"hal etmoq",    type:"Verb"},
    {korean:"변화하다",  uzbek:"o'zgarish",    type:"Verb"},
    {korean:"불행하다",  uzbek:"baxtsiz",    type:"Adjective"},
    {korean:"즐거운",  uzbek:"xursand",    type:"Adjective"},
    {korean:"두려운",  uzbek:"qo‘rqinchli",    type:"Adjective"},
    {korean:"친숙하다",  uzbek:"tanish",    type:"Adjective"},
    {korean:"차차",  uzbek:"asta-sekin",    type:"Adverb"},
    {korean:"하여튼",  uzbek:"har holda",    type:"Adverb"},
    {korean:"두유",  uzbek:"Soya suti",    type:"Noun"},
    {korean:"라떼",  uzbek:"Latte",    type:"Noun"},
    {korean:"카푸치노",  uzbek:"Kapuchino",    type:"Noun"},
    {korean:"에스프레소",  uzbek:"Espresso",    type:"Noun"},
    {korean:"아메리카노",  uzbek:"Americano",    type:"Noun"},
    {korean:"아이스티",  uzbek:"Muzli choy",    type:"Noun"},
    {korean:"녹차라떼",  uzbek:"Yashil choy latte",    type:"Noun"},
    {korean:"밀크티",  uzbek:"Sutli choy",    type:"Noun"},
    {korean:"변경하다",  uzbek:"o'zgartirmoq",    type:"Verb"},
    {korean:"포함하다",  uzbek:"o'z ichiga olmoq",    type:"Verb"},
    {korean:"추구하다",  uzbek:"izlanmoq",    type:"Verb"},
    {korean:"설정하다",  uzbek:"sozlamoq",    type:"Verb"},
    {korean:"지정하다",  uzbek:"belgilamoq",    type:"Verb"},
    {korean:"재정의하다",  uzbek:"qayta ta'riflamoq",    type:"Verb"},
    {korean:"희망찬",  uzbek:"umidli",    type:"Adjective"},
    {korean:"상처받은",  uzbek:"jarohatlangan",    type:"Adjective"},
    {korean:"결혼한",  uzbek:"turmush qurgan",    type:"Adjective"},
    {korean:"신선한",  uzbek:"yangi",    type:"Adjective"},
    {korean:"아무리",  uzbek:"qancha",    type:"Adverb"},
    {korean:"어떻게든",  uzbek:"qandaydir tarzda",    type:"Adverb"},
    {korean:"보바티",  uzbek:"Bobochali choy",    type:"Noun"},
    {korean:"생수",  uzbek:"Butilgan suv",    type:"Noun"},
    {korean:"미네랄워터",  uzbek:"Mineral suv",    type:"Noun"},
    {korean:"얼음물",  uzbek:"Muzli suv",    type:"Noun"},
    {korean:"레몬에이드",  uzbek:"Limonat",    type:"Noun"},
    {korean:"자몽에이드",  uzbek:"Greypfrut limonati",    type:"Noun"},
    {korean:"망고에이드",  uzbek:"Mango limonati",    type:"Noun"},
    {korean:"스무디",  uzbek:"Smuzi",    type:"Noun"},
    {korean:"대체하다",  uzbek:"o'zgartirmoq",    type:"Verb"},
    {korean:"관련하다",  uzbek:"aloqador bo'lmoq",    type:"Verb"},
    {korean:"파악하다",  uzbek:"tushunmoq",    type:"Verb"},
    {korean:"평가하다",  uzbek:"baholamoq",    type:"Verb"},
    {korean:"설명하다",  uzbek:"tushuntirmoq",    type:"Verb"},
    {korean:"연구하다",  uzbek:"tadqiq qilmoq",    type:"Verb"},
    {korean:"신비로운",  uzbek:"sirli",    type:"Adjective"},
    {korean:"고통스러운",  uzbek:"og‘riqli",    type:"Adjective"},
    {korean:"해로운",  uzbek:"zararli",    type:"Adjective"},
    {korean:"중요한",  uzbek:"muhim",    type:"Adjective"},
    {korean:"비교적",  uzbek:"nisbatan",    type:"Adverb"},
    {korean:"가끔씩",  uzbek:"ba'zan",    type:"Adverb"},
    {korean:"프라푸치노",  uzbek:"Frappuccino",    type:"Noun"},
    {korean:"모카",  uzbek:"Mokka",    type:"Noun"},
    {korean:"코코아",  uzbek:"Kakao",    type:"Noun"},
    {korean:"핫초코",  uzbek:"Issiq shokolad",    type:"Noun"},
    {korean:"마카롱",  uzbek:"Makaron",    type:"Noun"},
    {korean:"크루아상",  uzbek:"Kruvasan",    type:"Noun"},
    {korean:"도넛",  uzbek:"Donut",    type:"Noun"},
    {korean:"타르트",  uzbek:"Tart",    type:"Noun"},
    {korean:"준비하다",  uzbek:"tayyorlamoq",    type:"Verb"},
    {korean:"허락하다",  uzbek:"ruxsat bermoq",    type:"Verb"},
    {korean:"발달하다",  uzbek:"rivojlanmoq",    type:"Verb"},
    {korean:"확인하다",  uzbek:"tekshirmoq",    type:"Verb"},
    {korean:"반대하다",  uzbek:"qarshi bo'lmoq",    type:"Verb"},
    {korean:"전시하다",  uzbek:"ko‘rsatmoq",    type:"Verb"},
    {korean:"환상적인",  uzbek:"ajoyib",    type:"Adjective"},
    {korean:"조심스러운",  uzbek:"ehtiyotkor",    type:"Adjective"},
    {korean:"외로운",  uzbek:"yolg‘iz",    type:"Adjective"},
    {korean:"만족한",  uzbek:"mamnun",    type:"Adjective"},
    {korean:"유독",  uzbek:"aynan",    type:"Adverb"},
    {korean:"끊임없이",  uzbek:"doimiy",    type:"Adverb"},
    {korean:"푸딩",  uzbek:"Puding",    type:"Noun"},
    {korean:"젤리",  uzbek:"Jeli",    type:"Noun"},
    {korean:"아이스크림",  uzbek:"Muzqaymoq",    type:"Noun"},
    {korean:"셔벗",  uzbek:"Sherbet",    type:"Noun"},
    {korean:"와플",  uzbek:"Vafli",    type:"Noun"},
    {korean:"팬케이크",  uzbek:"Pancake",    type:"Noun"},
    {korean:"푸라프",  uzbek:"Parfait",    type:"Noun"},
    {korean:"피낭시에",  uzbek:"Financier",    type:"Noun"},
    {korean:"동의하다",  uzbek:"rozilik bermoq",    type:"Verb"},
    {korean:"변화하다",  uzbek:"o'zgarish",    type:"Verb"},
    {korean:"설계하다",  uzbek:"loyihalamoq",    type:"Verb"},
    {korean:"요구하다",  uzbek:"talab qilmoq",    type:"Verb"},
    {korean:"연구하다",  uzbek:"tadqiq qilmoq",    type:"Verb"},
    {korean:"해결하다",  uzbek:"hal etmoq",    type:"Verb"},
    {korean:"배부른",  uzbek:"to‘q",    type:"Adjective"},
    {korean:"이른",  uzbek:"erta",    type:"Adjective"},
    {korean:"늦은",  uzbek:"kech",    type:"Adjective"},
    {korean:"활기찬",  uzbek:"jozibador",    type:"Adjective"},
    {korean:"지속적으로",  uzbek:"davomiy",    type:"Adverb"},
    {korean:"기본적으로",  uzbek:"asosan",    type:"Adverb"},
    {korean:"까눌레",  uzbek:"Canelé",    type:"Noun"},
    {korean:"카스테라",  uzbek:"Kastella",    type:"Noun"},
    {korean:"떡",  uzbek:"Guruchli pirog",    type:"Noun"},
    {korean:"약식",  uzbek:"Shirin guruch",    type:"Noun"},
    {korean:"수정과",  uzbek:"Dolchin ichimligi",    type:"Noun"},
    {korean:"식혜",  uzbek:"Shirin guruch ichimligi",    type:"Noun"},
    {korean:"엿",  uzbek:"Koreyscha toffee",    type:"Noun"},
    {korean:"과자",  uzbek:"Snack",    type:"Noun"},
    {korean:"모집하다",  uzbek:"to‘plamoq",    type:"Verb"},
    {korean:"설치하다",  uzbek:"o‘rnatmoq",    type:"Verb"},
    {korean:"보관하다",  uzbek:"saqlamoq",    type:"Verb"},
    {korean:"수정하다",  uzbek:"tuzatmoq",    type:"Verb"},
    {korean:"제출하다",  uzbek:"topshirmoq",    type:"Verb"},
    {korean:"포기하다",  uzbek:"voz kechmoq",    type:"Verb"},
    {korean:"사소한",  uzbek:"kichik",    type:"Adjective"},
    {korean:"재미없는",  uzbek:"zerikarli",    type:"Adjective"},
    {korean:"친절한",  uzbek:"mehribon",    type:"Adjective"},
    {korean:"위험한",  uzbek:"xavfli",    type:"Adjective"},
    {korean:"정기적으로",  uzbek:"muntazam",    type:"Adverb"},
    {korean:"교대로",  uzbek:"navbat bilan",    type:"Adverb"},
    {korean:"칩",  uzbek:"Chips",    type:"Noun"},
    {korean:"과일",  uzbek:"Meva",    type:"Noun"},
    {korean:"사과",  uzbek:"Olma",    type:"Noun"},
    {korean:"배",  uzbek:"Anor",    type:"Noun"},
    {korean:"감",  uzbek:"Persimmon",    type:"Noun"},
    {korean:"귤",  uzbek:"Mandarinka",    type:"Noun"},
    {korean:"포도",  uzbek:"Uzum",    type:"Noun"},
    {korean:"딸기",  uzbek:"Qulupnay",    type:"Noun"},
    {korean:"자랑하다",  uzbek:"maqtanmoq",    type:"Verb"},
    {korean:"다가가다",  uzbek:"yaqinlashmoq",    type:"Verb"},
    {korean:"끌다",  uzbek:"tortmoq",    type:"Verb"},
    {korean:"불러오다",  uzbek:"chaqirib kelmoq",    type:"Verb"},
    {korean:"지나다",  uzbek:"o‘tmoq",    type:"Verb"},
    {korean:"나가다",  uzbek:"chiqmoq",    type:"Verb"},
    {korean:"무거운",  uzbek:"og‘ir",    type:"Adjective"},
    {korean:"가벼운",  uzbek:"yengil",    type:"Adjective"},
    {korean:"확실한",  uzbek:"aniq",    type:"Adjective"},
    {korean:"불확실한",  uzbek:"noaniq",    type:"Adjective"},
    {korean:"차례로",  uzbek:"navbatma-navbat",    type:"Adverb"},
    {korean:"가끔가다",  uzbek:"vaqti-vaqti bilan",    type:"Adverb"},
    {korean:"바나나",  uzbek:"Banan",    type:"Noun"},
    {korean:"파인애플",  uzbek:"Ananas",    type:"Noun"},
    {korean:"수박",  uzbek:"Tarvuz",    type:"Noun"},
    {korean:"참외",  uzbek:"Melon",    type:"Noun"},
    {korean:"복숭아",  uzbek:"Shaftoli",    type:"Noun"},
    {korean:"자두",  uzbek:"O'rik",    type:"Noun"},
    {korean:"체리",  uzbek:"O'rik",    type:"Noun"},
    {korean:"블루베리",  uzbek:"Mavi berry",    type:"Noun"},
    {korean:"지나가다",  uzbek:"o‘tib ketmoq",    type:"Verb"},
    {korean:"적다",  uzbek:"yozmoq",    type:"Verb"},
    {korean:"배우다",  uzbek:"o‘rganmoq",    type:"Verb"},
    {korean:"넣다",  uzbek:"qo‘ymoq",    type:"Verb"},
    {korean:"기록하다",  uzbek:"yozib qo‘ymoq",    type:"Verb"},
    {korean:"미루다",  uzbek:"kechiktirmoq",    type:"Verb"},
    {korean:"소중한",  uzbek:"qadrli",    type:"Adjective"},
    {korean:"열정적인",  uzbek:"ishtiyoq bilan",    type:"Adjective"},
    {korean:"기쁜",  uzbek:"xursand",    type:"Adjective"},
    {korean:"우울한",  uzbek:"g‘amgin",    type:"Adjective"},
    {korean:"문득",  uzbek:"birdaniga",    type:"Adverb"},
    {korean:"가벼운",  uzbek:"engil",    type:"Adverb"},
    {korean:"크랜베리",  uzbek:"Qizil berry",    type:"Noun"},
    {korean:"망고",  uzbek:"Mango",    type:"Noun"},
    {korean:"키위",  uzbek:"Kivi",    type:"Noun"},
    {korean:"레몬",  uzbek:"Limon",    type:"Noun"},
    {korean:"라임",  uzbek:"Limetta",    type:"Noun"},
    {korean:"자몽",  uzbek:"Greypfrut",    type:"Noun"},
    {korean:"아보카도",  uzbek:"Avokado",    type:"Noun"},
    {korean:"파파야",  uzbek:"Papaya",    type:"Noun"},
    {korean:"가져가다",  uzbek:"olib bormoq",    type:"Verb"},
    {korean:"나가다",  uzbek:"chiqmoq",    type:"Verb"},
    {korean:"지키다",  uzbek:"saqlamoq",    type:"Verb"},
    {korean:"발전시키다",  uzbek:"rivojlantirmoq",    type:"Verb"},
    {korean:"설명하다",  uzbek:"tushuntirmoq",    type:"Verb"},
    {korean:"발생하다",  uzbek:"yuzaga kelmoq",    type:"Verb"},
    {korean:"자부심 있는",  uzbek:"faxrlanuvchi",    type:"Adjective"},
    {korean:"침착한",  uzbek:"xotirjam",    type:"Adjective"},
    {korean:"겸손한",  uzbek:"kamtar",    type:"Adjective"},
    {korean:"성격 좋은",  uzbek:"yaxshi xarakterli",    type:"Adjective"},
    {korean:"신중하게",  uzbek:"ehtiyotkorlik bilan",    type:"Adverb"},
    {korean:"간단하게",  uzbek:"oddiy qilib",    type:"Adverb"},
    {korean:"멜론",  uzbek:"Melon",    type:"Noun"},
    {korean:"코코넛",  uzbek:"Koko nut",    type:"Noun"},
    {korean:"밤",  uzbek:"Qaymoq",    type:"Noun"},
    {korean:"호두",  uzbek:"Yong'oq",    type:"Noun"},
    {korean:"아몬드",  uzbek:"Badam",    type:"Noun"},
    {korean:"땅콩",  uzbek:"Yer yong'oq",    type:"Noun"},
    {korean:"캐슈넛",  uzbek:"Keshyu",    type:"Noun"},
    {korean:"피스타치오",  uzbek:"Pista",    type:"Noun"},
    {korean:"증가하다",  uzbek:"oshmoq",    type:"Verb"},
    {korean:"정리하다",  uzbek:"tartibga solmoq",    type:"Verb"},
    {korean:"보호하다",  uzbek:"himoya qilmoq",    type:"Verb"},
    {korean:"설치하다",  uzbek:"o‘rnatmoq",    type:"Verb"},
    {korean:"관리하다",  uzbek:"boshqarish",    type:"Verb"},
    {korean:"발생하다",  uzbek:"yuzaga kelmoq",    type:"Verb"},
    {korean:"나쁜 성격의",  uzbek:"yomon xarakterli",    type:"Adjective"},
    {korean:"시원한",  uzbek:"salqin",    type:"Adjective"},
    {korean:"맛있는",  uzbek:"mazali",    type:"Adjective"},
    {korean:"특별한",  uzbek:"maxsus",    type:"Adjective"},
    {korean:"점차",  uzbek:"asta-sekin",    type:"Adverb"},
    {korean:"신속하게",  uzbek:"tezda",    type:"Adverb"},
    {korean:"헤이즐넛",  uzbek:"Gazi yong'oq",    type:"Noun"},
    {korean:"피칸",  uzbek:"Pikan",    type:"Noun"},
    {korean:"대추",  uzbek:"Jujube",    type:"Noun"},
    {korean:"건포도",  uzbek:"Quritilgan uzum",    type:"Noun"},
    {korean:"무화과",  uzbek:"Inja",    type:"Noun"},
    {korean:"올리브",  uzbek:"Zaytun",    type:"Noun"},
    {korean:"자두",  uzbek:"O'rik",    type:"Noun"},
    {korean:"베리",  uzbek:"Berry",    type:"Noun"},
    {korean:"확인하다",  uzbek:"tekshirmoq",    type:"Verb"},
    {korean:"전달하다",  uzbek:"etkazmoq",    type:"Verb"},
    {korean:"해결하다",  uzbek:"hal etmoq",    type:"Verb"},
    {korean:"나가다",  uzbek:"chiqmoq",    type:"Verb"},
    {korean:"올리다",  uzbek:"ko‘tarish",    type:"Verb"},
    {korean:"낮추다",  uzbek:"pasaytirmoq",    type:"Verb"},
    {korean:"무미건조한",  uzbek:"behudak",    type:"Adjective"},
    {korean:"진지한",  uzbek:"jiddiy",    type:"Adjective"},
    {korean:"경쾌한",  uzbek:"quvnoq",    type:"Adjective"},
    {korean:"엉뚱한",  uzbek:"g‘alati",    type:"Adjective"},
    {korean:"전혀",  uzbek:"umuman",    type:"Adverb"},
    {korean:"드물게",  uzbek:"kamdan-kam",    type:"Adverb"},
    {korean:"라즈베리",  uzbek:"Qizil berry",    type:"Noun"},
    {korean:"블랙베리",  uzbek:"Qora berry",    type:"Noun"},
    {korean:"엘더베리",  uzbek:"Elderberry",    type:"Noun"},
    {korean:"고구마",  uzbek:"Shirin kartoshka",    type:"Noun"},
    {korean:"감자",  uzbek:"Kartoshka",    type:"Noun"},
    {korean:"옥수수",  uzbek:"Makkajo'xori",    type:"Noun"},
    {korean:"당근",  uzbek:"Sabzi",    type:"Noun"},
    {korean:"호박",  uzbek:"Qovoq",    type:"Noun"},
    {korean:"자극하다",  uzbek:"rag‘batlantirmoq",    type:"Verb"},
    {korean:"알리다",  uzbek:"xabardor qilmoq",    type:"Verb"},
    {korean:"설명하다",  uzbek:"tushuntirmoq",    type:"Verb"},
    {korean:"등록하다",  uzbek:"ro‘yxatdan o‘tkazmoq",    type:"Verb"},
    {korean:"해결하다",  uzbek:"hal etmoq",    type:"Verb"},
    {korean:"축하하다",  uzbek:"tabriklamoq",    type:"Verb"},
    {korean:"다정한",  uzbek:"mehribon",    type:"Adjective"},
    {korean:"성숙한",  uzbek:"yetuk",    type:"Adjective"},
    {korean:"희망적인",  uzbek:"umidvor",    type:"Adjective"},
    {korean:"변덕스러운",  uzbek:"beqaror",    type:"Adjective"},
    {korean:"속히",  uzbek:"tezda",    type:"Adverb"},
    {korean:"세밀하게",  uzbek:"batafsil",    type:"Adverb"},
    {korean:"오이",  uzbek:"Bodring",    type:"Noun"},
    {korean:"가지",  uzbek:"Qovun",    type:"Noun"},
    {korean:"피망",  uzbek:"Bulb chili",    type:"Noun"},
    {korean:"고추",  uzbek:"Qalampir",    type:"Noun"},
    {korean:"양파",  uzbek:"Piyoz",    type:"Noun"},
    {korean:"마늘",  uzbek:"Sarimsoq",    type:"Noun"},
    {korean:"생강",  uzbek:"Zanjabil",    type:"Noun"},
    {korean:"버섯",  uzbek:"Qo'ziqorin",    type:"Noun"},
    {korean:"세우다",  uzbek:"o‘rnatmoq",    type:"Verb"},
    {korean:"촉진하다",  uzbek:"rag‘batlantirmoq",    type:"Verb"},
    {korean:"제공하다",  uzbek:"taqdim etmoq",    type:"Verb"},
    {korean:"고치다",  uzbek:"tuzatmoq",    type:"Verb"},
    {korean:"응답하다",  uzbek:"javob bermoq",    type:"Verb"},
    {korean:"재개하다",  uzbek:"qayta boshlamoq",    type:"Verb"},
    {korean:"도전적인",  uzbek:"qiyin",    type:"Adjective"},
    {korean:"경외스러운",  uzbek:"hurmatli",    type:"Adjective"},
    {korean:"분노한",  uzbek:"g‘azablangan",    type:"Adjective"},
    {korean:"착한",  uzbek:"yaxshi",    type:"Adjective"},
    {korean:"고요하게",  uzbek:"tinch",    type:"Adverb"},
    {korean:"분명히",  uzbek:"aniq",    type:"Adverb"},
    {korean:"시금치",  uzbek:"Spanach",    type:"Noun"},
    {korean:"브로콜리",  uzbek:"Brokkoli",    type:"Noun"},
    {korean:"콜리플라워",  uzbek:"Karfiol",    type:"Noun"},
    {korean:"케일",  uzbek:"Kele",    type:"Noun"},
    {korean:"양배추",  uzbek:"Karahol",    type:"Noun"},
    {korean:"상추",  uzbek:"Salat bargi",    type:"Noun"},
    {korean:"로메인",  uzbek:"Romaine",    type:"Noun"},
    {korean:"무",  uzbek:"Radish",    type:"Noun"},
    {korean:"증가하다",  uzbek:"oshmoq",    type:"Verb"},
    {korean:"접하다",  uzbek:"uchrashmoq",    type:"Verb"},
    {korean:"시도하다",  uzbek:"urinish",    type:"Verb"},
    {korean:"보장하다",  uzbek:"kafolat bermoq",    type:"Verb"},
    {korean:"저장하다",  uzbek:"saqlamoq",    type:"Verb"},
    {korean:"조정하다",  uzbek:"tartibga solmoq",    type:"Verb"},
    {korean:"적극적인",  uzbek:"faol",    type:"Adjective"},
    {korean:"소극적인",  uzbek:"passiv",    type:"Adjective"},
    {korean:"차분한",  uzbek:"tinch",    type:"Adjective"},
    {korean:"부드러운",  uzbek:"yumshoq",    type:"Adjective"},
    {korean:"애초에",  uzbek:"dastlab",    type:"Adverb"},
    {korean:"억지로",  uzbek:"majburan",    type:"Adverb"},
    {korean:"배추",  uzbek:"Napa kapib",    type:"Noun"},
    {korean:"쪽파",  uzbek:"Yong'oq piyoz",    type:"Noun"},
    {korean:"파",  uzbek:"Qalam piyoz",    type:"Noun"},
    {korean:"대파",  uzbek:"Katta piyoz",    type:"Noun"},
    {korean:"샐러리",  uzbek:"Seleriy",    type:"Noun"},
    {korean:"아스파라거스",  uzbek:"Asparagu",    type:"Noun"},
    {korean:"아티초크",  uzbek:"Artichoke",    type:"Noun"},
    {korean:"비트",  uzbek:"Beets",    type:"Noun"},
    {korean:"주의하다",  uzbek:"ehtiyot bo‘lmoq",    type:"Verb"},
    {korean:"대화하다",  uzbek:"suhbatlashmoq",    type:"Verb"},
    {korean:"전하다",  uzbek:"yetkazmoq",    type:"Verb"},
    {korean:"복사하다",  uzbek:"nusxalamoq",    type:"Verb"},
    {korean:"원하다",  uzbek:"xohlamoq",    type:"Verb"},
    {korean:"바라보다",  uzbek:"qaramoq",    type:"Verb"},
    {korean:"격렬한",  uzbek:"qattiq",    type:"Adjective"},
    {korean:"화려한",  uzbek:"hashamatli",    type:"Adjective"},
    {korean:"소심한",  uzbek:"qo‘rqoq",    type:"Adjective"},
    {korean:"화끈한",  uzbek:"ishtiyoqli",    type:"Adjective"},
    {korean:"가까스로",  uzbek:"qiyinchilik bilan",    type:"Adverb"},
    {korean:"흥미롭게",  uzbek:"qiziqish bilan",    type:"Adverb"},
    {korean:"순무",  uzbek:"Turnip",    type:"Noun"},
    {korean:"콩",  uzbek:"Fasol",    type:"Noun"},
    {korean:"렌틸",  uzbek:"Lental",    type:"Noun"},
    {korean:"완두콩",  uzbek:"No'r kabob",    type:"Noun"},
    {korean:"강낭콩",  uzbek:"Qizil fasol",    type:"Noun"},
    {korean:"병아리콩",  uzbek:"Tovuq fasoli",    type:"Noun"},
    {korean:"새싹",  uzbek:"Sprout",    type:"Noun"},
    {korean:"샐러드",  uzbek:"Salat",    type:"Noun"},
    {korean:"떠나다",  uzbek:"ketmoq",    type:"Verb"},
    {korean:"안되다",  uzbek:"bo‘lmaslik",    type:"Verb"},
    {korean:"예측하다",  uzbek:"bashorat qilmoq",    type:"Verb"},
    {korean:"분석하다",  uzbek:"tahlil qilmoq",    type:"Verb"},
    {korean:"저축하다",  uzbek:"jamg‘armoq",    type:"Verb"},
    {korean:"재정의하다",  uzbek:"qayta belgilash",    type:"Verb"},
    {korean:"귀여운",  uzbek:"yoqimli",    type:"Adjective"},
    {korean:"부유한",  uzbek:"boy",    type:"Adjective"},
    {korean:"가난한",  uzbek:"kambag‘al",    type:"Adjective"},
    {korean:"독특한",  uzbek:"o‘ziga xos",    type:"Adjective"},
    {korean:"부주의하게",  uzbek:"ehtiyotsiz",    type:"Adverb"},
    {korean:"초조하게",  uzbek:"xavotirda",    type:"Adverb"},
    {korean:"해바라기씨",  uzbek:"Quyosh urug'i",    type:"Noun"},
    {korean:"호박씨",  uzbek:"Qovoq urug'i",    type:"Noun"},
    {korean:"참깨",  uzbek:"Sesame urug'i",    type:"Noun"},
    {korean:"치아씨",  uzbek:"Chia urug'i",    type:"Noun"},
    {korean:"햄",  uzbek:"Ham",    type:"Noun"},
    {korean:"베이컨",  uzbek:"Bacon",    type:"Noun"},
    {korean:"소시지",  uzbek:"Kolbasa",    type:"Noun"},
    {korean:"스테이크",  uzbek:"Steyk",    type:"Noun"},
    {korean:"허락하다",  uzbek:"ruxsat bermoq",    type:"Verb"},
    {korean:"공유하다",  uzbek:"baham ko‘rmoq",    type:"Verb"},
    {korean:"지시하다",  uzbek:"ko‘rsatma bermoq",    type:"Verb"},
    {korean:"나타나다",  uzbek:"paydo bo‘lish",    type:"Verb"},
    {korean:"가입하다",  uzbek:"a'zo bo‘lish",    type:"Verb"},
    {korean:"청구하다",  uzbek:"talab qilmoq",    type:"Verb"},
    {korean:"여유로운",  uzbek:"bo‘sh",    type:"Adjective"},
    {korean:"풍부한",  uzbek:"boy",    type:"Adjective"},
    {korean:"새롭고",  uzbek:"yangi",    type:"Adjective"},
    {korean:"낯선",  uzbek:"tanish emas",    type:"Adjective"},
    {korean:"기쁜 마음으로",  uzbek:"xursand bo‘lib",    type:"Adverb"},
    {korean:"느긋하게",  uzbek:"sabr-toqat bilan",    type:"Adverb"},
    {korean:"불고기",  uzbek:"Bulgogi",    type:"Noun"},
    {korean:"닭강정",  uzbek:"Sweet crispy chicken",    type:"Noun"},
    {korean:"삼겹살",  uzbek:"Pork belly",    type:"Noun"},
    {korean:"족발",  uzbek:"Pig's trotters",    type:"Noun"},
    {korean:"보쌈",  uzbek:"Wrapped pork",    type:"Noun"},
    {korean:"순대",  uzbek:"Korean sausage",    type:"Noun"},
    {korean:"곱창",  uzbek:"Intestine",    type:"Noun"},
    {korean:"양꼬치",  uzbek:"Lamb skewers",    type:"Noun"},
    {korean:"선택하다",  uzbek:"tanlamoq",    type:"Verb"},
    {korean:"보고하다",  uzbek:"xabar bermoq",    type:"Verb"},
    {korean:"불리다",  uzbek:"chaqirilmoq",    type:"Verb"},
    {korean:"복구하다",  uzbek:"tiklash",    type:"Verb"},
    {korean:"이루다",  uzbek:"amalga oshirmoq",    type:"Verb"},
    {korean:"강화하다",  uzbek:"mustahkamlash",    type:"Verb"},
    {korean:"투명한",  uzbek:"shaffof",    type:"Adjective"},
    {korean:"흐릿한",  uzbek:"xiralashgan",    type:"Adjective"},
    {korean:"더운",  uzbek:"issiq",    type:"Adjective"},
    {korean:"시원한",  uzbek:"salqin",    type:"Adjective"},
    {korean:"열심히",  uzbek:"qat'iyat bilan",    type:"Adverb"},
    {korean:"자주",  uzbek:"tez-tez",    type:"Adverb"},
    {korean:"탕수육",  uzbek:"Sweet and sour pork",    type:"Noun"},
    {korean:"떡갈비",  uzbek:"Grilled short rib patties",    type:"Noun"},
    {korean:"샤브샤브",  uzbek:"Shabu-shabu",    type:"Noun"},
    {korean:"샤브샤브 - Shab",  uzbek:"habu",    type:"Noun"},
    {korean:"핫도그",  uzbek:"Hot dog",    type:"Noun"},
    {korean:"카레",  uzbek:"Curry",    type:"Noun"},
    {korean:"짜장면",  uzbek:"Black bean noodles",    type:"Noun"},
    {korean:"짬뽕",  uzbek:"Spicy seafood noodle soup",    type:"Noun"},
    {korean:"발휘하다",  uzbek:"ko‘rsatmoq",    type:"Verb"},
    {korean:"중단하다",  uzbek:"to‘xtatmoq",    type:"Verb"},
    {korean:"요약하다",  uzbek:"qisqartirmoq",    type:"Verb"},
    {korean:"확인하다",  uzbek:"tasdiqlamoq",    type:"Verb"},
    {korean:"설명하다",  uzbek:"tushuntirmoq",    type:"Verb"},
    {korean:"추적하다",  uzbek:"izdan tushmoq",    type:"Verb"},
    {korean:"자극적인",  uzbek:"rag‘batlantiruvchi",    type:"Adjective"},
    {korean:"무딘",  uzbek:"o'tkir emas",    type:"Adjective"},
    {korean:"날카로운",  uzbek:"o'tkir",    type:"Adjective"},
    {korean:"엷은",  uzbek:"yupqa",    type:"Adjective"},
    {korean:"바짝",  uzbek:"tik turib",    type:"Adverb"},
    {korean:"끝내",  uzbek:"oxirida",    type:"Adverb"},
    {korean:"탕면",  uzbek:"Soup noodles",    type:"Noun"},
    {korean:"냉면",  uzbek:"Cold noodles",    type:"Noun"},
    {korean:"칼국수",  uzbek:"Knife-cut noodles",    type:"Noun"},
    {korean:"칼국수 - Knif",  uzbek:"ut noodles",    type:"Noun"},
    {korean:"비빔면",  uzbek:"Spicy mixed noodles",    type:"Noun"},
    {korean:"쫄면",  uzbek:"Chewy noodles",    type:"Noun"},
    {korean:"라면",  uzbek:"Instant noodles",    type:"Noun"},
    {korean:"떡볶이",  uzbek:"Spicy rice cake",    type:"Noun"},
    {korean:"증명하다",  uzbek:"isbotlamoq",    type:"Verb"},
    {korean:"검토하다",  uzbek:"ko‘rib chiqmoq",    type:"Verb"},
    {korean:"소개하다",  uzbek:"tanishtirmoq",    type:"Verb"},
    {korean:"회복하다",  uzbek:"tiklamoq",    type:"Verb"},
    {korean:"저장하다",  uzbek:"saqlamoq",    type:"Verb"},
    {korean:"작동하다",  uzbek:"ishlamoq",    type:"Verb"},
    {korean:"진한",  uzbek:"qalin",    type:"Adjective"},
    {korean:"따뜻한",  uzbek:"iliq",    type:"Adjective"},
    {korean:"진한",  uzbek:"kuchli",    type:"Adjective"},
    {korean:"소음이 많은",  uzbek:"shovqinli",    type:"Adjective"},
    {korean:"간단히",  uzbek:"oddiy qilib",    type:"Adverb"},
    {korean:"순조롭게",  uzbek:"muammosiz",    type:"Adverb"},
    {korean:"순두부찌개",  uzbek:"Soft tofu stew",    type:"Noun"},
    {korean:"된장찌개",  uzbek:"Soybean paste stew",    type:"Noun"},
    {korean:"김치찌개",  uzbek:"Kimchi stew",    type:"Noun"},
    {korean:"부대찌개",  uzbek:"Army stew",    type:"Noun"},
    {korean:"갈비탕",  uzbek:"Short rib soup",    type:"Noun"},
    {korean:"설렁탕",  uzbek:"Ox bone soup",    type:"Noun"},
    {korean:"육개장",  uzbek:"Spicy beef soup",    type:"Noun"},
    {korean:"해장국",  uzbek:"Hangover soup",    type:"Noun"},
    {korean:"포함하다",  uzbek:"o‘z ichiga olmoq",    type:"Verb"},
    {korean:"변하다",  uzbek:"o‘zgarish",    type:"Verb"},
    {korean:"변명하다",  uzbek:"bahona qilmoq",    type:"Verb"},
    {korean:"방지하다",  uzbek:"oldini olish",    type:"Verb"},
    {korean:"완료하다",  uzbek:"tugatmoq",    type:"Verb"},
    {korean:"조절하다",  uzbek:"boshqarish",    type:"Verb"},
    {korean:"지루한",  uzbek:"zerikarli",    type:"Adjective"},
    {korean:"활기 넘치는",  uzbek:"quvnoq",    type:"Adjective"},
    {korean:"긴급한",  uzbek:"shoshilinch",    type:"Adjective"},
    {korean:"자주 바뀌는",  uzbek:"tez-tez o'zgaruvchan",    type:"Adjective"},
    {korean:"자연스럽게",  uzbek:"tabiiy tarzda",    type:"Adverb"},
    {korean:"단호히",  uzbek:"qat'iy",    type:"Adverb"},
    {korean:"콩나물국",  uzbek:"Bean sprout soup",    type:"Noun"},
    {korean:"미역국",  uzbek:"Seaweed soup",    type:"Noun"},
    {korean:"북어국",  uzbek:"Dried pollack soup",    type:"Noun"},
    {korean:"김밥",  uzbek:"Seaweed rice roll",    type:"Noun"},
    {korean:"주먹밥",  uzbek:"Rice ball",    type:"Noun"},
    {korean:"삼각김밥",  uzbek:"Triangle kimbap",    type:"Noun"},
    {korean:"밥버거",  uzbek:"Rice burger",    type:"Noun"},
    {korean:"치즈볼",  uzbek:"Cheese ball",    type:"Noun"},
    {korean:"연결하다",  uzbek:"bog‘lamoq",    type:"Verb"},
    {korean:"대답하다",  uzbek:"javob bermoq",    type:"Verb"},
    {korean:"의사소통하다",  uzbek:"aloqa qilish",    type:"Verb"},
    {korean:"추가하다",  uzbek:"qo‘shmoq",    type:"Verb"},
    {korean:"보존하다",  uzbek:"saqlamoq",    type:"Verb"},
    {korean:"시도하다",  uzbek:"urinish",    type:"Verb"},
    {korean:"깊은",  uzbek:"chuqur",    type:"Adjective"},
    {korean:"얕은",  uzbek:"sayoz",    type:"Adjective"},
    {korean:"훌륭한",  uzbek:"a'lo",    type:"Adjective"},
    {korean:"놀라운",  uzbek:"hayratlanarli",    type:"Adjective"},
    {korean:"동시",  uzbek:"bir vaqtda",    type:"Adverb"},
    {korean:"후에",  uzbek:"keyin",    type:"Adverb"},
    {korean:"피자",  uzbek:"Pizza",    type:"Noun"},
    {korean:"햄버거",  uzbek:"Hamburger",    type:"Noun"},
    {korean:"샌드위치",  uzbek:"Sandwich",    type:"Noun"},
    {korean:"핫도그",  uzbek:"Hot dog",    type:"Noun"},
    {korean:"토스트",  uzbek:"Toast",    type:"Noun"},
    {korean:"바게트",  uzbek:"Baguette",    type:"Noun"},
    {korean:"베이글",  uzbek:"Bagel",    type:"Noun"},
    {korean:"크로와상",  uzbek:"Croissant",    type:"Noun"},
    {korean:"체결하다",  uzbek:"imzolamoq",    type:"Verb"},
    {korean:"이끌다",  uzbek:"boshqarish",    type:"Verb"},
    {korean:"진입하다",  uzbek:"kirish",    type:"Verb"},
    {korean:"발사하다",  uzbek:"otmoq",    type:"Verb"},
    {korean:"수용하다",  uzbek:"qabul qilmoq",    type:"Verb"},
    {korean:"집행하다",  uzbek:"amalga oshirmoq",    type:"Verb"},
    {korean:"비참한",  uzbek:"qayg‘uli",    type:"Adjective"},
    {korean:"화사한",  uzbek:"rang-barang",    type:"Adjective"},
    {korean:"견고한",  uzbek:"mustahkam",    type:"Adjective"},
    {korean:"깨지기 쉬운",  uzbek:"oson singadigan",    type:"Adjective"},
    {korean:"원래",  uzbek:"aslida",    type:"Adverb"},
    {korean:"전통적으로",  uzbek:"an'anaviy tarzda",    type:"Adverb"}
    ];